name: Docker Build

on:
  push:
    branches:
      - master  # or main, based on your branch name
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t resume-analyzer .

      # Optional: Run container to check if it runs
      - name: Run container test
        run: |
          docker run -d -p 8501:8501 resume-analyzer
